/**
 * KPI Data Service - Phase 4 Sprint 1
 *
 * Core business logic for KPI data submissions with:
 * - Count form submission (Sprint 4.1)
 * - Version tracking (Sprint 4.4 - prepared here)
 * - Audit trail (handled by database triggers)
 * - Security validation
 * - Transaction safety
 *
 * Design decisions:
 * - Version number hardcoded to 1 for Sprint 4.1
 * - Audit logging handled by PostgreSQL triggers (see migration 002)
 * - RLS policies enforce user_id matching at database level
 * - Status always starts as 0 (pending)
 * - Submitted_date auto-generated by database
 */

import { supabase } from '../db';
import {
  CountFormInput,
  KPIData,
  KPIDataResponse,
  MeasurementType,
  getStatusLabel,
  getDataSourceLabel
} from '../types/kpiData';
import {
  validateCountForm,
  validateComponentOwnership,
  checkDeadline,
  validateMeasurementType,
  hasPendingSubmission,
  getComponentWithOKR
} from './kpiDataValidationService';
import {
  ValidationError,
  ConflictError,
  NotFoundError,
  AppError
} from '../middleware/errorHandler';

/**
 * Submit count form data (measurement_type = 0)
 *
 * Flow:
 * 1. Validate form inputs (value, evidence_link, notes)
 * 2. Verify component exists and user has access
 * 3. Check measurement type matches (must be count)
 * 4. Check deadline hasn't passed
 * 5. Check for existing pending submission
 * 6. Insert into User_KPI_Data with status=0 (pending)
 * 7. Return enriched response with component/OKR details
 *
 * @param user_id - Authenticated user's UUID
 * @param user_role - User's role name
 * @param input - Count form submission data
 * @returns Enriched submission response
 * @throws ValidationError - Invalid input data
 * @throws ForbiddenError - Access denied or deadline passed
 * @throws NotFoundError - Component doesn't exist
 * @throws ConflictError - Duplicate pending submission
 */
export async function submitCountForm(
  user_id: string,
  user_role: string,
  input: CountFormInput
): Promise<KPIDataResponse> {
  try {
    // Step 1: Validate form inputs
    validateCountForm(input);

    // Step 2: Verify component exists and user has access
    const component = await validateComponentOwnership(
      user_id,
      user_role,
      input.kpi_component_id
    );

    // Step 3: Verify measurement type is count (0)
    validateMeasurementType(component, MeasurementType.COUNT);

    // Step 4: Check deadline hasn't passed
    checkDeadline(component);

    // Step 5: Check for existing pending submission
    const hasPending = await hasPendingSubmission(user_id, input.kpi_component_id);
    if (hasPending) {
      throw new ConflictError(
        'You already have a pending submission for this component. ' +
        'Wait for manager approval before submitting again.'
      );
    }

    // Step 6: Prepare submission data
    const submissionData = {
      user_id: user_id,
      okr_id: component.okr_id, // Denormalized for reporting efficiency
      kpi_component_id: input.kpi_component_id,
      value: input.value,
      evidence_link: input.evidence_link,
      notes: input.notes || null,
      data_source: input.data_source || 0, // Default to manual
      status: 0, // Pending approval
      version_number: 1, // Hardcoded for Sprint 4.1, will be dynamic in Sprint 4.4
      submitted_date: new Date().toISOString()
    };

    // Step 7: Insert into database
    const { data: submission, error: insertError } = await supabase
      .from('"User_KPI_Data"')
      .insert(submissionData)
      .select()
      .single();

    if (insertError) {
      console.error('Database insert error:', insertError);

      // Check for unique constraint violation
      if (insertError.code === '23505') {
        throw new ConflictError(
          'A submission with this version number already exists. This should not happen.'
        );
      }

      throw new AppError('Failed to create submission', 500);
    }

    if (!submission) {
      throw new AppError('Submission created but no data returned', 500);
    }

    // Step 8: Return enriched response
    return enrichSubmissionResponse(submission, component);
  } catch (error) {
    // Re-throw known errors
    if (error instanceof AppError) {
      throw error;
    }

    // Log unexpected errors
    console.error('Unexpected error in submitCountForm:', error);
    throw new AppError('An unexpected error occurred while processing your submission', 500);
  }
}

/**
 * Enriches a raw submission with component and OKR details
 * Provides better UX by including context in API responses
 *
 * @param submission - Raw database record
 * @param component - Component with OKR details (optional, will fetch if not provided)
 * @returns Enriched submission response
 */
async function enrichSubmissionResponse(
  submission: any,
  component?: any
): Promise<KPIDataResponse> {
  // Fetch component details if not provided
  if (!component) {
    component = await getComponentWithOKR(submission.kpi_component_id);
  }

  return {
    id: submission.id,
    user_id: submission.user_id,
    kpi_component: {
      id: component.id,
      name: component.component_name,
      target_value: component.target_value,
      unit: component.unit || '',
      measurement_type: component.measurement_type
    },
    okr: {
      id: component.okr.id,
      title: component.okr.okr_title,
      year: component.okr.year,
      quarter: component.okr.quarter,
      deadline_at: component.okr.deadline_at
    },
    value: submission.value,
    numerator: submission.numerator,
    denominator: submission.denominator,
    version_number: submission.version_number,
    status: submission.status,
    status_label: getStatusLabel(submission.status),
    evidence_link: submission.evidence_link,
    submitted_date: submission.submitted_date,
    notes: submission.notes,
    response_count: submission.response_count,
    data_source: submission.data_source,
    data_source_label: getDataSourceLabel(submission.data_source)
  };
}

/**
 * Get user's KPI data submissions with optional filtering
 *
 * Rules:
 * - Users can only see their own submissions (enforced by RLS)
 * - By default, returns only latest versions
 * - Can include all versions with include_history=true
 * - Supports filtering by OKR, component, status
 *
 * @param user_id - Authenticated user's UUID
 * @param filters - Optional query filters
 * @returns Array of submissions
 */
export async function getUserKPIData(
  user_id: string,
  filters: {
    okr_id?: string;
    kpi_component_id?: string;
    status?: number;
    include_history?: boolean;
  } = {}
): Promise<KPIDataResponse[]> {
  try {
    // Build query
    let query = supabase
      .from('"User_KPI_Data"')
      .select(`
        *,
        kpi_component:kpi_component_id (
          id,
          component_name,
          target_value,
          unit,
          measurement_type,
          okr:okr_id (
            id,
            okr_title,
            year,
            quarter,
            deadline_at
          )
        )
      `)
      .eq('user_id', user_id);

    // Apply filters
    if (filters.okr_id) {
      query = query.eq('okr_id', filters.okr_id);
    }

    if (filters.kpi_component_id) {
      query = query.eq('kpi_component_id', filters.kpi_component_id);
    }

    if (filters.status !== undefined) {
      query = query.eq('status', filters.status);
    }

    // If not including history, only get latest versions
    if (!filters.include_history) {
      // This is simplified for Sprint 4.1 - will be enhanced in Sprint 4.4
      query = query.order('version_number', { ascending: false });
    }

    // Execute query
    const { data, error } = await query;

    if (error) {
      console.error('Error fetching KPI data:', error);
      throw new AppError('Failed to retrieve submissions', 500);
    }

    if (!data || data.length === 0) {
      return [];
    }

    // Transform to enriched responses
    const enriched = await Promise.all(
      data.map(async (submission) => {
        // Extract nested component data (Supabase returns it differently based on query)
        const component = Array.isArray(submission.kpi_component)
          ? submission.kpi_component[0]
          : submission.kpi_component;

        const okr = Array.isArray(component.okr) ? component.okr[0] : component.okr;

        return {
          id: submission.id,
          user_id: submission.user_id,
          kpi_component: {
            id: component.id,
            name: component.component_name,
            target_value: component.target_value,
            unit: component.unit || '',
            measurement_type: component.measurement_type
          },
          okr: {
            id: okr.id,
            title: okr.okr_title,
            year: okr.year,
            quarter: okr.quarter,
            deadline_at: okr.deadline_at
          },
          value: submission.value,
          numerator: submission.numerator,
          denominator: submission.denominator,
          version_number: submission.version_number,
          status: submission.status,
          status_label: getStatusLabel(submission.status),
          evidence_link: submission.evidence_link,
          submitted_date: submission.submitted_date,
          notes: submission.notes,
          response_count: submission.response_count,
          data_source: submission.data_source,
          data_source_label: getDataSourceLabel(submission.data_source)
        };
      })
    );

    return enriched;
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }

    console.error('Unexpected error in getUserKPIData:', error);
    throw new AppError('An unexpected error occurred while retrieving submissions', 500);
  }
}

/**
 * Placeholder for percentage form submission (Sprint 4.2)
 */
export async function submitPercentageForm(): Promise<KPIDataResponse> {
  throw new AppError('Percentage form submission not yet implemented (Sprint 4.2)', 501);
}

/**
 * Placeholder for score form submission (Sprint 4.3)
 */
export async function submitScoreForm(): Promise<KPIDataResponse> {
  throw new AppError('Score form submission not yet implemented (Sprint 4.3)', 501);
}

/**
 * Placeholder for boolean form submission (Sprint 4.3)
 */
export async function submitBooleanForm(): Promise<KPIDataResponse> {
  throw new AppError('Boolean form submission not yet implemented (Sprint 4.3)', 501);
}
